### ISSUE TITLE
TypeScript implementation (idea)

### ISSUE THREAD

**Issue by Brian3647** [chiquicalris-dev/shofy#6]
## Explanation

As TypeScript is the _future\*_ of JavaScript, would be possible to re-code it in TypeScript (I can do this, it isn't that hard); with a stricter code development to make sure the code gets the fast and efficient as possible.

Also, this way could make more people want to contribute

 ## Suggested tools:
- TypeScript itself
- ESLint
- GitHub actions

## How?

We could get some parts of the code from [this template](https://github.com/Brian3647/typescript-discord-bot-template), and create custom types (it's easy)

## Further explanation

*: TypeScript is not going to delete completely JavaScript, but it's beeing used more and more and it gives a better developing experience.

**Comment by Brian3647** [comment]
@jc-discdev What do you think?

**Comment by chiquicalris-dev** [comment]
It can be a good idea, also, I saw that you are interested in the future of the project, I would like to comment some things by direct message, could you contact me through `Chiqui#1337`?

**Comment by Brian3647** [comment]
Yes, I'm Brian3647 on Discord

**Comment by chiquicalris-dev** [comment]
`Brian#3647`?

**Comment by Brian3647** [comment]
Yes

**Comment by jc-discdev** [comment]
I think we could use TypeScript and Discord.JS because we could do more things if we combine both.
@chiquicalris-dev @Brian3647 What do you think guys?

**Comment by Brian3647** [comment]
It's a good idea actually, I did that multiple times and it is interesting

**Comment by jc-discdev** [comment]
@Brian3647 Could you accept me on Discord, I am JCGAMER_YT#1339

**Comment by Brian3647** [comment]
> @Brian3647 Could you accept me on Discord, I am JCGAMER_YT#1339

It says you don't accept friend request, you have to add me: Brian3647#0001

**Comment by Brian3647** [comment]
Brian3647\#0001*

**Comment by Brian3647** [comment]
Wtf the 0s disappear

**Comment by jc-discdev** [comment]
> It's a good idea actually, I did that multiple times and it is interesting

Then perfect.

**Comment by jc-discdev** [comment]
Yes idk why.
